site_name: Mcblend
site_url: https://nusiq.github.io/mcblend/
repo_url: https://github.com/Nusiq/mcblend
edit_uri: ""
site_description: A Blender addon for creating and animating Minecraft Bedrock Edition models.
site_author: Nusiq

nav:
    - Overview: index.md
    - Limitations: limitations/index.md
    - Conversion rules: conversion_rules/index.md
    - GUI: gui/index.md
    - Importing and exporting files: importing_and_exporting/index.md
    - Animating effects: animating_effects/index.md
    - UV-groups: uv_groups/index.md
    - Texture customization (advanced): texture_customization/index.md
    - Tips and tricks: tips_and_tricks/index.md

theme:
    name: readthedocs
    favicon: img/favicon.ico
    titles_only: false

markdown_extensions:
    - admonition
